version: '3'

services:
  db:
    image: postgres
    container_name: tictactoe_db
    ports:
      - 5555:5432
    env_file:
      - back-end/.env
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: tictactoe_node
    build: ./back-end
    ports:
      - 5000:5000
    env_file:
      - back-end/.env
    depends_on:
      - db

volumes:
  postgres: